backend:
  name: git-gateway
  branch: master
  repo: viktorfa/vikfand-portfolio
media_folder: static/images
media_folder_relative: true
collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image 1", name: "image", widget: "image", required: false }
      - { label: "Image 2", name: "image2", widget: "image", required: false }
      - { label: "Image 3", name: "image3", widget: "image", required: false }
      - { label: "Order", name: "order", widget: "number", valueType: "int" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "config"
    label: "Config"
    label_singular: "Config"
    extension: json
    files:
      - file: siteConfig.json
        label: Config
        name: config
        fields:
          - name: siteName
            label: Site Name
            widget: string
          - name: siteDescription
            label: Site Description
            widget: string
          - name: siteUrl
            label: Site Url
            widget: string
